plymouth: update config manjaroiso: versions bump

diff --git a/plymouth/encrypt_hook.patch b/plymouth/encrypt_hook.patch
--- a/plymouth/encrypt_hook.patch
+++ b/plymouth/encrypt_hook.patch
@@ -1,16 +1,15 @@
---- encrypt_hook	2011-07-30 08:58:50.000000000 +0200
-+++ encrypt_hook	2011-07-30 09:04:19.935861787 +0200
-@@ -69,10 +69,9 @@
-                     echo ""
-                     echo "A password is required to access the ${cryptname} volume:"
-
--                    #loop until we get a real password
--                    while ! eval /sbin/cryptsetup luksOpen ${cryptdev} ${cryptname} ${cryptargs} ${CSQUIET}; do
--                        sleep 2;
--                    done
-+                    plymouth ask-for-password --prompt="Password for ${cryptname} volume" --dont-pause-progress --number-of-tries=5 --command="/sbin/cryptsetup luksOpen --key-file=- ${cryptdev} ${cryptname} ${cryptargs} ${CSQUIET}"
-+                    sleep 2;
+--- encrypt_hook.orig	2012-07-13 21:18:49.161032887 +0300
++++ encrypt_hook	2012-07-13 21:20:53.687701165 +0300
+@@ -76,10 +76,9 @@
+                 echo ""
+                 echo "A password is required to access the ${cryptname} volume:"
+ 
+-                #loop until we get a real password
+-                while ! eval cryptsetup luksOpen ${resolved} ${cryptname} ${cryptargs} ${CSQUIET}; do
++                    plymouth ask-for-password --prompt="Password for ${cryptname} volume" --dont-pause-progress --number-of-tries=5 --command="/sbin/cryptsetup luksOpen --key-file=- ${cryptdev} ${cryptname} ${CSQUIET}"
+                     sleep 2;
+-                done
 +
-                 fi
-                 if [ -e "/dev/mapper/${cryptname}" ]; then
-                     if [ ${DEPRECATED_CRYPT} -eq 1 ]; then
+             fi
+             if [ -e "/dev/mapper/${cryptname}" ]; then
+                 if [ ${DEPRECATED_CRYPT} -eq 1 ]; then
